apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/manifests/overlays/appstudio-staging-cluster?ref=adcda66c2568ad3a8d1f64e6d377bea0a9bed5ab


images:
  - name: \${COMMON_IMAGE}
    newName: quay.io/anjoseph/gitops-service
    newTag: latest

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
